services:
  hytale:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hytale
    environment:
      INIT_MEMORY: "16G"
      MAX_MEMORY: "16G"
      AOT: true
    stdin_open: true
    tty: true
    ports:
      - "5520:5520/udp"
    volumes:
    - launcher:/app/launcher
    - gamefiles:/app/data
volumes:
  launcher:
  gamefiles:

